version: '3'

services:
  server: 
    build: ./server
    command: npm start
    ports:
      - "3001:3001"
    volumes:
      - /fullcycle/app/server

  client: 
    build: ./client
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - /fullcycle/app/client